i = int()
f = float()
s = str()
a = list()
t = tuple()
h = dict()
b = bool()

print(i)
print(isinstance(i, int))
print(f)
print(isinstance(f, float))
print(s)
print(isinstance(s, str))
print(a)
print(isinstance(a, list))
print(t)
print(isinstance(t, tuple))
print(h)
print(isinstance(h, dict))
print(b)
print(isinstance(b, bool))